name: test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: "aureliojargas/clitest"
          path: bin/clitest
      - run: sudo apt install zsh shellcheck
        if: ${{ runner.os == 'Linux' }}
      - run: brew install shellcheck
        if: ${{ runner.os == 'macOS' }}
      - run: PATH=$GITHUB_WORKSPACE/bin/clitest:$PATH make testall
        shell: zsh {0}
